config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome", as: 'welcome'

  get "about" => "application#about"

  resources :repositories

  #We only accept html request to block request like /users/robots.txt
  resources :users, constraints: {format: /(html)/}, only: [:index, :search, :show] do
    get 'search', on: :collection
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  namespace :api do
    namespace :v0 do
      resources :users, constraints: { format: /(json)/ }, only: [:index, :show], param: :login
      resources :languages, only: [:index]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include User::Rank
  include User::Token
  has_many :repositories, dependent: :destroy
  has_many :authentication_providers, dependent: :destroy
  validates :login, presence: true, uniqueness: true
  before_save { |user| user.login.downcase! }
  
  def to_param
    login
  end
  
  def self.find_as_sorted(ids)
    if ids.length > 0
      values = []
      ids.each_with_index do |id, index|
        values << "(#{id}, #{index + 1})"
      end
      self.joins("JOIN (VALUES #{values.join(",")}) as x (id, ordering) ON #{table_name}.id = x.id").order('x.ordering').group('x.ordering')
    else
      self
    end
  end
end

app/models/user/rank.rb
module User::Rank
  def user_ranks
    repos = repositories.with_language.select("count(*) as repository_count, sum(stars) AS stars_count, language").group(:language).order("stars_count DESC")
    repos.map do |r|
      UserRank.new(self, r.language, r["stars_count"], r["repository_count"])
    end
  end
  
  def update_rank
    RankWorker.perform_async(self.id)
  end

  def remove_ranks
    repos = repositories.with_language.select("count(*) as repository_count, sum(stars) AS stars_count, language").group(:language).order("stars_count DESC")
    repos.each do |r|
      UserRank.new(self, r.language, nil, nil).remove
    end
  end
end

app/models/user/token.rb
module User::Token
  def token
    authentication_providers.first.try(:token)
  end
end

app/controllers/api/v0/users_controller.rb
# encoding: utf-8
module Api
  module V0
    class UsersController < ApiController
      include Documentation::SwaggerUsersControllerMod

      def index
        user_list_presenter = UserListPresenter.new(params)
        user_ranks = user_list_presenter.user_ranks
        respond(UserRanks::IndexSerializer.new(user_ranks).serializable_hash)
      end

      def show
        user = User.where(login: params[:login].try(:downcase).try(:strip)).first
        return respond({}, :not_found) unless user

        respond(UserRanks::ShowSerializer.new(user).serializable_hash, :ok)
      end

    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user_list_presenter = UserListPresenter.new(params)
  end
  
  def search
    show_user(params[:login])
    rescue ActiveRecord::RecordNotFound => e
      redirect_to welcome_path, alert: "User #{ERB::Util.html_escape params[:login]} not found. If you are looking for your own profile you can <a href='/auth/github'>refresh it from Github</a>"
  end

  def show
    show_user(params[:id])
  end
  
  private 
  
  def show_user(login)
    @user = User.where(login: login.try(:downcase).try(:strip)).first || not_found
    
    @user_presenter = UserPresenter.new(@user)
    render action: 'show'
  end
end

app/views/users/index.html.erb
<% content_for :head do %>
  <title> <%= @user_list_presenter.language.capitalize %> <%= @user_list_presenter.title %> | Git Awards</title>
  <meta name="description" content="List of top <%= @user_list_presenter.language.capitalize %> developers <%= @user_list_presenter.title %>"/>
  <meta name="robots" content="nofollow">
<% end %>

<div class="row">
  <div class="col-xs-12">
    <h1>Top <%= @user_list_presenter.language.capitalize %> GitHub developers <%= @user_list_presenter.title %></h1>
  </div>
</div>
<br>

<div class="row">
  <%= form_tag users_path, :method => 'get' do %>
    <%= hidden_field_tag(:type, @user_list_presenter.type) %>
    <div class="col-lg-2 col-xs-4">
      <%= select_tag :language, options_for_select(@user_list_presenter.languages, @user_list_presenter.language), :class => "form-control" %>
    </div>
    <% if @user_list_presenter.show_location_input? %>
      <div class="col-lg-4 col-xs-4">
        <%= @user_list_presenter.location_input %>
      </div>
    <% end %>
    <div class="col-lg-6 col-xs-4 pull-left">
      <button type="submit" class="btn btn-default">Submit</button>
    </div>
  <% end %>
</div>
<br>

<div class="row">
  <div class="col-xs-12">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Username</th>
          <th><%= @user_list_presenter.rank_label %></th>
          <th>Stars</th>
        </tr>
      </thead>

      <tbody>
        <% user_ranks = @user_list_presenter.user_ranks %>
        <% if user_ranks.empty? %>
          <tr>
            <td><%= @user_list_presenter.empty_message %> </td>
          </tr>
        <% end %>
        <% @user_list_presenter.user_ranks.each do |user_rank| %>
          <tr>
            <td><%= link_to(image_tag(user_rank.user.gravatar_url, :class => "thumbnail avatar"), user_path(user_rank.user)) %></td>
            <td class="username"><%= link_to(user_rank.user.login, user_path(user_rank.user.login))%></td>
            <td><%= @user_list_presenter.ranking(user_rank) %></td>
            <td><%= user_rank.stars_count %> <i class="fa fa-star star"></i></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<div class="row">
  <div class="col-xs-12">
    <%= paginate @user_list_presenter.user_ranks %>
  </div>
</div>

app/views/users/show.html.erb
<% content_for :head do %>
  <title> <%= @user.login %> | Git Awards </title>
  <meta name="robots" content="noindex, nofollow">
<% end %>

<div class="row">
  <div class="col-md-3 info" >
    <div class="row">
      <%= image_tag @user.gravatar_url, :class => "thumbnail avatar-bg"%>
      <h2><span class="mega-octicon octicon-mark-github"></span> <strong><%= link_to @user.login, "https://github.com/#{@user.login}" %></strong></h2>
      <p><%= @user_presenter.city %></p>
      <p><%= @user_presenter.country %></p>
      <%= @user_presenter.best_rank_tweet %>
      <%= link_to "Refresh your profile", '/auth/github', :class => "btn btn-success" if session[:user_id].nil? %>
    </div>
    <hr/>
    <div class="row sponsor">
      <p><b>This project is hosted by exoscale.ch thanks for their support !</b></p>
    </div>
  </div>
  <div class="col-md-9">
    <% if @user_presenter.user_ranks.empty? %>
      <div class="no-info">
        <p><strong>That's embarrassing...</strong></p>
        <p><strong>We don't have any info for your account. Maybe you don't have any repository on GitHub, or GitHub couldn't guess the language for any for your repos. </strong></p>
        <p>You can manually search for <%= link_to "top github developers in your city", users_path %> </p>
      </div>
    <% end %>
    
    <% @user_presenter.user_ranks.each do |user_rank| %>
      <% presenter = UserRankPresenter.new(user_rank) %>
      <div class="row">
        <div class="col-md-3 info">
          <p><%= user_rank.language%> ranking</p>
        </div>
        <div class="col-md-9 pull-left">
          
          <table class="table rank">
            <tbody>
              <tr>
                <%= presenter.city_infos %>
              </tr>
              <tr>
                <%= presenter.country_infos %>
              </tr>
              <tr>
                <%= presenter.world_infos %>
              </tr>
              <tr>
                <td class="col-md-3">
                  <%= link_to "https://github.com/search?" + {q: "user:#{@user.login} language:#{user_rank.language}"}.to_query, target: '_blank' do %>
                    Repos :
                  <% end %>
                </td>
                <td><%= user_rank.repository_count %> <span class="octicon octicon-repo"></span></td>
              </tr>
              <tr>
                <td class="col-md-3">Stars :</td>
                <td><%= user_rank.stars_count %> <span class="octicon octicon-star"></span></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <hr/>
    <% end %>
  </div>
</div>