config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome", as: 'welcome'

  get "about" => "application#about"

  resources :repositories

  #We only accept html request to block request like /users/robots.txt
  resources :users, constraints: {format: /(html)/}, only: [:index, :search, :show] do
    get 'search', on: :collection
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  namespace :api do
    namespace :v0 do
      resources :users, constraints: { format: /(json)/ }, only: [:index, :show], param: :login
      resources :languages, only: [:index]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  caches_action :about
  
  def welcome
  end
  
  def about
  end
  
  def not_found
    raise ActiveRecord::RecordNotFound.new('Not Found')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/about.html.erb
<% content_for :head do %>
  <title> GitHub ranking FAQ | Git Awards</title>
  <meta name="description" content="Frequently asked questions about your GitHub ranking" />
  <link rel="canonical" href=<%= about_url %> />
<% end %>

<div class="col-lg-12">
  <h1>About Git Awards</h1>
  
  <br>
  
  <p>I love feedback, if you have any questions or comments, send me a tweet: <a href="https://twitter.com/vdaubry">@vdaubry</a></p>
  <br>
  
  <h2>FAQ</h2>
  
  <div class="panel-group" id="accordion">
    <div class="faq_header">Ranking questions</div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_rank">How do you calculate my ranking?</a>
        </h4>
      </div>
      <div id="collapse_rank" class="panel-collapse collapse in">
        <div class="panel-body">
          First your score is computed for each language using this formula:
          <div class="">
            <pre>
              <code class="language-html" data-lang="html">sum(stars) + (1.0 - 1.0/count(repositories))</code>
            </pre>
          </div>
          
          <p>Then you are ranked according to your score compared to other developers with repositories in the same language or in the same location (by city, by country or worldwide).</p>
          
          <p>If you're interested in the ranking you should have a look at the SQL query that generates the ranking table: <a href="https://github.com/vdaubry/github-awards/blob/master/sql/rank.sql">rank.sql</a></p>
          
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_data">How did you get the data?</a>
        </h4>
      </div>
      <div id="collapse_data" class="panel-collapse collapse">
        <div class="panel-body">
          Git Awards retrieves data from 2 sources:
            <ul>
              <li>
                <a href="https://developer.github.com/v3/">GitHub API</a>
              </li>
              <li>
                <a href="https://www.githubarchive.org/">GitHub Archive</a>
              </li>
            </ul>
          
          For a detailed explanation of how the data was processed, see the project readme: <a href="https://github.com/vdaubry/github-awards">https://github.com/vdaubry/github-awards</a>
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_missing_stars">Why are some of my stars missing?</a>
        </h4>
      </div>
      <div id="collapse_missing_stars" class="panel-collapse collapse">
        <div class="panel-body">
          We get the number of stars for each repo from <a href="https://www.githubarchive.org/">GitHub Archive</a>. Most likely the data for some of your repos are not up to date.

          We plan to add GitHub connect and allow you to ask for a refresh. In the meantime you can reach me on Twitter if some of your data is not accurate: @vdaubry
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_github_search">Can't you already do that with GitHub search?</a>
        </h4>
      </div>
      <div id="collapse_github_search" class="panel-collapse collapse">
        <div class="panel-body">
          The GitHub search is great and you should use it everytime it can answer your question. However there are some things that can't be done with GitHub search:
          
          <ul>
            <li>
              The main difference is that you can't search for YOUR ranking with GitHub search.
            </li>
            <li>
              You cannot search for top users by total number of stars.
            </li>
            <li>
              Location on GitHub is a plain text field, so if you search for users in "San Francisco", you won't find users with location "SF, CA" or any other variations. You cannot search for a user by country if they have only filled in their city.
            </li>
          </ul>
          
          Git Awards geocodes user locations, so provided you filled your city in your location, you can have your ranking in your city, in your country, and worldwide.
        </div>
      </div>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_organization">Why is my organization not shown?</a>
        </h4>
      </div>
      <div id="collapse_organization" class="panel-collapse collapse">
        <div class="panel-body">
          At the moment I have excluded organizations from the ranking calculation in order to have a user only ranking. If you would like to have an organization ranking send me a tweet and we'll talk about it.
        </div>
      </div>
    </div>
  </div>
  <div class="faq_header">General questions</div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_who">Who am I?</a>
      </h4>
    </div>
    <div id="collapse_who" class="panel-collapse collapse">
      <div class="panel-body">
        I'm vincent daubry, I'm a Ruby developer living in Paris. You can find more about me and my project <a href="https://github.com/vdaubry">on GitHub</a>.
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_contribute">I think this is fun, how can I help?</a>
      </h4>
    </div>
    <div id="collapse_contribute" class="panel-collapse collapse">
      <div class="panel-body">
        There are many simple things that can help this project greatly:

        <ul>
          <li>
            Send a tweet supporting this project.
          </li>
          <li>
            You are probably sitting next to another developer right now, tell them about Git Awards.
          </li>
          <li>
            If you want to contribute to the project, that's amazing! Open an issue on GitHub and let's talk about it.
          </li>
        </ul>

      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_privacy">What about privacy?</a>
      </h4>
    </div>
    <div id="collapse_privacy" class="panel-collapse collapse">
      <div class="panel-body">
        I care a lot about this project not being creepy. It doesn't display your name or your email, you cannot search for someone by name or get access to their email. Only GitHub username, avatar, repository list, location, and repository language.

        Though we don't display it, the database might contain information <strong>already publicly available</strong> on your GitHub profile:
        <ul>
          <li>
            Email
          </li>
          <li>
            Full name
          </li>
          <li>
            Location
          </li>
          <li>
            Picture (avatar)
          </li>
          <li>
            Website or blog URL
          </li>
          <li>
            Company
          </li>
        </ul>

        If you want to edit or remove any of this information, you can reach me on twitter.

      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapse_credits">Credits</a>
      </h4>
    </div>
    <div id="collapse_credits" class="panel-collapse collapse">
      <div class="panel-body">
        Special thanks to Albine Corbière for coming with the name Git Awards
      </div>
    </div>
  </div>
</div>

app/views/application/welcome.html.erb
<%= content_for :head do %>
  <title> Git Awards : Discover your ranking on GitHub</title>
  <meta name="description" content="Discover your ranking on Github! Find out what is your rank by language, in your city and in your country"/>
  <link rel="canonical" href=<%= welcome_url %> />
<% end %>

<div class="col-lg-12 intro">
  <form class="" action="<%= search_users_path %>" accept-charset="UTF-8" method="get">
    <div class="col-xs-6 col-centered text-center" style="top:200px">
      <div class="row">
        <div class="col-xs-12">
          <label>Discover your ranking on GitHub</label>
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-md-3"></div>
        <div class="col-md-4">
          <input type="search" name="login" class="form-control" placeholder="Github username">
        </div>
        <div class="col-md-2">
          <button type="submit" class="btn btn-default">Search</button>
        </div>
      </div>
      <br>
      <br>
    </div>
  </form>
</div>