config/routes.rb
Rails.application.routes.draw do
  root to: "application#welcome", as: 'welcome'

  get "about" => "application#about"

  resources :repositories

  #We only accept html request to block request like /users/robots.txt
  resources :users, constraints: {format: /(html)/}, only: [:index, :search, :show] do
    get 'search', on: :collection
  end

  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#failure'

  namespace :api do
    namespace :v0 do
      resources :users, constraints: { format: /(json)/ }, only: [:index, :show], param: :login
      resources :languages, only: [:index]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/cupertino/jquery-ui.min.css">
    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://code.jquery.com/ui/1.11.2/jquery-ui.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.8.2/chosen.jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
    <%= favicon_link_tag 'favicon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    
    <!-- Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-59714064-1', 'auto');
      ga('send', 'pageview');
    </script>
    
    <%= yield :head %>
  </head>
  
  <body class="<%= "#{params[:controller]}_#{params[:action]}" %>">
    <div class="navbar navbar-default">
      <div class="container">
        <div class="navbar-header">
          <button  type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Git Awards', welcome_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse" id="navbar-collapse">
          <ul class="nav navbar-nav">
            <li>
              <form class="navbar-form navbar-left" action="<%= search_users_path %>" accept-charset="UTF-8" method="get">
                <input type="search" name="login" class="form-control" placeholder="GitHub username">
                <button type="submit" class="btn btn-default">Search</button>
              </form>
            </li>
            <li>
              <%= link_to 'Top users by city', users_path(city: "san francisco") %>
            </li>
            <li>
              <%= link_to 'Top users by country', users_path(country: "united states") %>
            </li>
            <li>
              <%= link_to 'Top users worldwide', users_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav">
            <li><a href="/about">About</a></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <% if flash[:alert] %>
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <strong>Warning!</strong> <%= flash[:alert].html_safe %>
        </div>
      <% end %>
      
      <% if flash[:info] %>
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= flash[:info] %>
        </div>
      <% end %>
      
      <%= yield %>
      
    </div>
  </body>
  <hr>
  <footer>
    <p><strong>Like this project? Support it by sending a </strong> <a href="http://twitter.com/share?text=What's your ranking on GitHub? Come check it out on Git Awards!&url=http://www.git-awards.com/&hashtags=GitHub" title="Share Git Awards on Twitter" target="_blank">tweet <i class="fa fa-twitter"></i></a></p>
    <p>Made by <a href="https://twitter.com/vdaubry">@vdaubry</a>. See source on <a href="https://github.com/vdaubry/github-awards">GitHub</a></p>
    <p>This project is not affiliated with the GitHub company in any way.</p>
  </footer>
</html>